apiVersion: v1
kind: Service
metadata:
  name: pages-service
  labels:
    name: pages-service
    app: pages-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pages-app
    name: pages-pod